apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service-deployment
spec:
  replicas: 2  # Specifies the number of instances
  selector:
    matchLabels:
      app: feedback-service
  template:
    metadata:
      labels:
        app: feedback-service
    spec:
      containers:
      - name: feedback-service
        image: dyoneus/feedback-service:latest  # Use the tag you used when building your Docker image
        ports:
        - containerPort: 5001  # The port your service listens on

---
apiVersion: v1
kind: Service
metadata:
  name: feedback-service
spec:
  type: NodePort  # Exposes the service on a port on each node in the cluster
  selector:
    app: feedback-service
  ports:
    - protocol: TCP
      port: 80  # The port that the service will be accessed through
      targetPort: 5001  # The container port to forward to
